### PR TITLE
fix(shape): Resolve errors when leaving page

### LINKED ISSUE #130: Shape demo causes error when navigating away
Steps:

1. Navigate to Shape demo
2. Navigate away by any means (arrow, sidebar, back button)

8 errors are reported, seemingly one for each of the ripples constructed in the shape catalog component:

image

### PR DESCRIPTION
**Pull request by kfranqueiro**
Fixes #130

### CODE REVIEW

File: src/ShapeCatalog.js [hunk 1]
```diff
@@ -38,7 +38,11 @@ class ShapeHero extends Component {
 }
 
 class ShapeDemos extends Component {
-  ripples = [];
+  constructor(props) {
+    super(props);
+    this.ripples = [];
```
Comment (moog16) [inline src/ShapeCatalog.js]: On next PR, we don't need to wrap this in the `constructor`. These could just live on the class like so:

```js
class ShapeDemos extends Component {
  ripples = [];
  initRipple = surfaceEl => surfaceEl && this.ripples.push(new MDCRipple(surfaceEl));
}
```

Comment (kfranqueiro) [reply src/ShapeCatalog.js]: When it's created this way, is ripples still effectively an instance variable? I was worried it was being created on the class.

At any rate, this matches exactly what we were already doing in ButtonCatalog. There's probably a few things we could clean up in general at some point in the future.

Comment (moog16) [reply src/ShapeCatalog.js]: They are instance variables, here is a codepen showing that https://codepen.io/moog16/pen/ZoJVrR.

But yes, there are a few places that we created those variables in constructors, so we'll need to clean up eventually.
