### PR TITLE
fix: style and font for header component

### LINKED ISSUE #17: Update HeaderBar with new design
- [x] Update HeaderBar colour to black
- [x] Make HeaderBar icon a back arrow on component pages (make icon a param?)
- [ ] Update HeaderBar typography
- [x] Update HeaderBar title to "MATERIAL COMPONENTS FOR WEB"

### PR DESCRIPTION
**Pull request by moog16**
fixes #17

### CODE REVIEW

File: src/HeaderBar.js [hunk 1]
```diff
@@ -6,18 +6,32 @@ import materialComponentsLogo from './images/ic_component_24px_white.svg';
...
         </div>
       </header>
     );
   }
+
+  renderLogo() {
+    const isAtComponentPath = window.location.pathname.split('/material-components-web-catalog').length > 1;
+
+    return (
+      <a href='/' className='material-icons mdc-top-app-bar__navigation-icon' title='Home'>
```
Comment (bonniezhou) [inline src/HeaderBar.js]: Just a note: the href was fixed in #33, be careful when merging.
